name: deploy-app-ci-cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy
        # Only run this step if the branch is main
      if: github.ref == 'refs/heads/main'
      env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
          curl "$deploy_url"
